name: Telegram Bot Notification

# Workflow triggers manually or by webhook events
on:
  workflow_dispatch:  # Manual trigger for testing
  issues:
    types: [opened]  # Example: Triggered when an issue is opened (for testing purposes)

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Data
      id: setup_data
      run: |
        # Save the leaderboard data to a JSON file
        echo '[
        {"name": "molecule", "wagered": {"today": 0, "this_week": 0, "all_time": 25.35}},
        {"name": "Flakeypooo", "wagered": {"today": 368.55, "this_week": 2525.86, "all_time": 3314.17}},
        {"name": "YoshiSupreme", "wagered": {"today": 0, "this_week": 263.24, "all_time": 8374.83}},
        {"name": "SCOOBOMAFIA", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Hooch13", "wagered": {"today": 5.02, "this_week": 1085.79, "all_time": 8688.28}},
        {"name": "Eunjo", "wagered": {"today": 0.28, "this_week": 664.37, "all_time": 4063.46}},
        {"name": "LeStrange", "wagered": {"today": 0, "this_week": 11.38, "all_time": 1469.3246}},
        {"name": "idkhowfakefeels", "wagered": {"today": 1600.99, "this_week": 520018.63, "all_time": 2240552.64}},
        {"name": "Malibu", "wagered": {"today": 0, "this_week": 0, "all_time": 20.14}},
        {"name": "TooTheMoonnnn", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Matteo001", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Tacopolice", "wagered": {"today": 0, "this_week": 0.92, "all_time": 1238.99}},
        {"name": "DeCentra", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Kpkplol", "wagered": {"today": 0, "this_week": 0, "all_time": 2585.54}},
        {"name": "Legit168", "wagered": {"today": 0, "this_week": 0, "all_time": 1.01075030652214}},
        {"name": "N8ball3r", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Whyburn", "wagered": {"today": 0, "this_week": 19.64, "all_time": 764.54}},
        {"name": "PoopdekStarburst", "wagered": {"today": 0, "this_week": 1.98, "all_time": 398.95}},
        {"name": "Elmgn", "wagered": {"today": 22.52, "this_week": 1849.067, "all_time": 5226.96}},
        {"name": "Gigachad124", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "justly-wretched-ruddy-duck", "wagered": {"today": 0, "this_week": 0, "all_time": 194.97}},
        {"name": "kartik1819", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Sogeking", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "shelbydee9892", "wagered": {"today": 0, "this_week": 19.45, "all_time": 10290.439}},
        {"name": "Hnels612", "wagered": {"today": 0, "this_week": 180.5399, "all_time": 566.477}},
        {"name": "scatterz", "wagered": {"today": 0, "this_week": 0, "all_time": 1436.17}},
        {"name": "Thecatberg", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Sintodamoon", "wagered": {"today": 0, "this_week": 0, "all_time": 142.401}},
        {"name": "Taylor01", "wagered": {"today": 0, "this_week": 8.4627, "all_time": 3828.7417}},
        {"name": "FiZZZZy", "wagered": {"today": 0, "this_week": 0, "all_time": 4849.32}},
        {"name": "wucaknshro", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Billybob", "wagered": {"today": 0, "this_week": 3.96, "all_time": 2175.7961}},
        {"name": "Surely", "wagered": {"today": 0, "this_week": 0, "all_time": 833.13}},
        {"name": "Wenmiracle", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Kristen", "wagered": {"today": 0, "this_week": 0, "all_time": 112.52}},
        {"name": "Stakeover", "wagered": {"today": 0, "this_week": 66.236, "all_time": 66.05}},
        {"name": "n6nazen", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "iamsoxo", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Skeffa", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "UWUxr", "wagered": {"today": 0, "this_week": 47.747, "all_time": 902.06}},
        {"name": "RalphG", "wagered": {"today": 141.14, "this_week": 208.533, "all_time": 1842.33}},
        {"name": "Goddox9", "wagered": {"today": 26.72, "this_week": 7932.99, "all_time": 24758.57}},
        {"name": "TheXerct", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Luffy", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Benderko", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Xiiwii288", "wagered": {"today": 0, "this_week": 0, "all_time": 4.668}},
        {"name": "HuffnPuff", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Hutch", "wagered": {"today": 0, "this_week": 0, "all_time": 32.99}},
        {"name": "dopezz", "wagered": {"today": 562.59, "this_week": 8584.57, "all_time": 59701.06}},
        {"name": "Gahlynco", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Krichard72", "wagered": {"today": 0, "this_week": 0, "all_time": 120.981}},
        {"name": "LedeKinky69", "wagered": {"today": 0, "this_week": 1012.94, "all_time": 1223.10}},
        {"name": "TheAnswer93", "wagered": {"today": 0, "this_week": 0, "all_time": 281.94}},
        {"name": "Wildblue54", "wagered": {"today": 0, "this_week": 0, "all_time": 0}},
        {"name": "Smurfyy88", "wagered": {"today": 0, "this_week": 27.79, "all_time": 285.01}},
        {"name": "figaroSS", "wagered": {"today": 23.11, "this_week": 23.007, "all_time": 414.86}},
        {"name": "ItsMeHades", "wagered": {"today": 0, "this_week": 2715.07, "all_time": 2807.35}},
        {"name": "Jereatiraza", "wagered": {"today": 0, "this_week": 128.67, "all_time": 163.09}}
        ]' > leaderboard.json
        
    - name: Handle Telegram Commands
      run: |
        # Extract the message from the GitHub event (or webhook)
        MESSAGE_TEXT="${{ github.event.issue.body }}"  # Example of pulling message from issue body
        
        if [[ $MESSAGE_TEXT == "/wager "* ]]; then
          NAME=$(echo $MESSAGE_TEXT | cut -d' ' -f2)
          WAGER=$(jq --arg name "$NAME" '.[] | select(.name==$name)' leaderboard.json)
          
          if [ -z "$WAGER" ]; then
            MESSAGE="No user found with name: $NAME"
          else
            TODAY=$(echo $WAGER | jq '.wagered.today')
            THIS_WEEK=$(echo $WAGER | jq '.wagered.this_week')
            ALL_TIME=$(echo $WAGER | jq '.wagered.all_time')
            MESSAGE="Name: $NAME\nWager Today: $TODAY\nWager This Week: $THIS_WEEK\nAll Time: $ALL_TIME"
          fi
        elif [[ $MESSAGE_TEXT == "/leaderboard_weekly" ]]; then
          MESSAGE="🏆 Top 10 Weekly Wagers 🏆\n"
          MESSAGE+=$(jq -r '. | sort_by(.wagered.this_week) | reverse | .[0:10] | to_entries[] | "\(.key + 1). \(.value.name) - \(.value.wagered.this_week)"' leaderboard.json)
        fi

        # Send the message to Telegram
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"

      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
